class Character {
  final String name;
  final List<String> traitNames;

  Character(this.name, this.traitNames);
}


List<Character> characters = [
  Character('Alistar', ['Ox Force', 'Aegis', 'Mascot']),
  Character('Annie', ['Gadgeteen', 'Ox Force', 'Spellslinger']),
  Character('Aphelios', ['Arsenal', 'Ox Force', 'Sureshot']),
  Character('Ashe', ['LaserCorps', 'Recon']),
  Character('Blitzcrank', ['Admin','Brawler']),
  Character('Camille', ['Renegade','Admin']),
  Character('Draven', ['Ace','Mecha: PRIME']),
  Character('Ekko', ['Prankster','Aegis','Star Guardian']),
  Character('Ezreal', ['Recon','Underground']),
  Character('Fiddlesticks', ['Threat','Corrupted']),
  Character('Fiora', ['Ox Force','Duelist']),
  Character('Galio', ['Civilian','Mascot']),
  Character('Gangplank', ['Supers','Duelist']),
  Character('Janna', ['Civilian','Spellslinger','Forecaster']),
  Character('Jax', ['Brawler','Mecha: PRIME']),
  Character('Jinx', ['Prankster','Anima Squad']),
  Character('Kaisa', ['Recon','Star Guardian']),
  Character('Kayle', ['Duelist','Underground']),
  Character('Leblanc', ['Hacker','Spellslinger','Admin']),
  Character('Lee Sin', ['Heart','Brawler','Supers']),
  Character('Leona', ['Mecha: PRIME','Aegis','Renegade']),
  Character('Lulu', ['Gadgeteen','Heart']),
  Character('Lux', ['Star Guardian','Spellslinger']),
  Character('Malphite', ['Supers','Mascot']),
  Character('Miss Fortune', ['Ace','Anima Squad']),
  Character('Mordekaiser', ['LaserCorps','Ace']),
  Character('Nasus', ['Anima Squad','Mascot']),
  Character('Nilah', ['Star Guardian','Duelist']),
  Character('Nunu', ['Gadgeteen','Mascot']),
  Character('Poppy', ['Gadgeteen','Defender']),
  Character('Rell', ['Star Guardian','Defender']),
  Character('Renekton', ['LaserCorps','Brawler']),
  Character('Riven', ['Anima Squad','Brawler','Defender']),
  Character('Samira', ['Ace','Sureshot','Underground']),
  Character('Sejuani', ['LaserCorps','Brawler']),
  Character('Senna', ['LaserCorps','Sureshot']),
  Character('Sett', ['Mecha: PRIME','Defender']),
  Character('Sivir', ['Civilian','Sureshot']),
  Character('Sona', ['Underground','Heart','Spellslinger']),
  Character('Soraka', ['Admin','Heart']),
  Character('Sylas', ['Renegade','Anima Squad']),
  Character('Syndra', ['Heart','Star Guardian']),
  Character('Taliyah', ['Star Guardian','Spellslinger']),
  Character('Talon', ['Ox Force','Renegade']),
  Character('Vayne', ['Duelist','Anima Squad','Recon']),
  Character('Vi', ['Underground','Brawler','Aegis']),
  Character('Viego', ['Ox Force','Renegade']),
  Character('Wukong', ['Mecha: PRIME','Defender']),
  Character('Yasuo', ['LaserCorps','Duelist']),
  Character('Yuumi', ['Star Guardian','Mascot','Heart']),
  Character('Zed', ['Hacker','LaserCorps','Duelist']),
  Character('Zoe', ['Hacker','Gadgeteen','Prankster']),
];
