class Character {
  final String name;
  final List<String> traitNames;

  Character(this.name, this.traitNames);
}


// TODO: Fill this out
List<Character> characters = [
  Character('Alistar', ['Ox Force', 'Aegis', 'Mascot']),
  Character('Annie', ['Gadgeteen', 'Ox Force', 'Spellslinger']),
  Character('Aphelios', ['Arsenal', 'Ox Force', 'Sureshot']),
  Character('Ashe', ['LaserCorps', 'Recon']),
  Character('Aurelion Sol', []),
  Character('Belveth', []),
  Character('Blitzcrank', []),
  Character('Camille', []),
  Character('Chogath', []),
  Character('Draven', []),
  Character('Ekko', []),
  Character('Ezreal', []),
  Character('Fiddlesticks', []),
  Character('Fiora', []),
  Character('Galio', []),
  Character('Gangplank', []),
  Character('Janna', []),
  Character('Jax', []),
  Character('Jinx', []),
  Character('Kaisa', []),
  Character('Kayle', []),
  Character('Leblanc', []),
  Character('Lee Sin', []),
  Character('Leona', []),
  Character('Lulu', []),
  Character('Lux', []),
  Character('Malphite', []),
  Character('Miss Fortune', []),
  Character('Mordekaiser', []),
  Character('Nasus', []),
  Character('Nilah', []),
  Character('Nunu', []),
  Character('Poppy', []),
  Character('Rammus', []),
  Character('Rell', []),
  Character('Renekton', []),
  Character('Riven', []),
  Character('Samira', []),
  Character('Sejuani', []),
  Character('Senna', []),
  Character('Sett', []),
  Character('Sivir', []),
  Character('Sona', []),
  Character('Soraka', []),
  Character('Sylas', []),
  Character('Syndra', []),
  Character('Taliyah', []),
  Character('Talon', []),
  Character('Urgot', []),
  Character('Vayne', []),
  Character('Velkoz', []),
  Character('Vi', []),
  Character('Viego', []),
  Character('Wukong', []),
  Character('Yasuo', []),
  Character('Yuumi', []),
  Character('Zac', []),
  Character('Zed', []),
  Character('Zoe', []),
];
