class Trait {
  final String name;
  final List<int> breakpoints;
  Trait(this.name,
  this.breakpoints);
}


// TODO: Fill this out, verify this
// If there's extras make sure to put the image in the assets path
List<Trait> traits = [
  Trait('Ace',[1,4]),
  Trait('Admin',[2,4,6]),
  Trait('Aegis',[2,3,4,5]),
  Trait('Anima Squad',[3,5,7]),
  Trait('Arsenal',[1]),
  Trait('Brawler',[2,4,6,8]),
  Trait('Civilian',[1,2,3]),
  Trait('Corrupted',[1]),
  Trait('Defender',[2,4,6]),
  Trait('Duelist',[2,4,6,8]),
  Trait('Forecaster',[1]),
  Trait('Gadgeteen',[3,5]),
  Trait('Hacker',[2,3,4]),
  Trait('Heart',[2,4,6]),
  Trait('LaserCorps',[3,5,7,9]),
  Trait('Mascot',[2,4,6,8]),
  Trait('Mecha PRIME',[3,5]),
  Trait('Ox Force',[2,4,6,8]),
  Trait('Prankster',[2,3]),
  Trait('Recon',[2,3,4]),
  Trait('Renegade',[3,6]),
  Trait('Spellslinger',[2,4,6,8]),
  Trait('Star Guardian',[3,5,7,9]),
  Trait('Supers',[3]),
  Trait('Sureshot',[2,4]),
  Trait('Threat',[1]),
  Trait('Underground',[3,4,5,6]),
];


class QuizTrait {
  final Trait trait;
  final int desiredLevel;
  QuizTrait(this.trait, this.desiredLevel);
}

// TODO: Fill this out, make at least 30 hardcoded quizzes
class DailyQuiz {
  final List<QuizTrait> quizTraits;
  final List<List<String>> correctCharacters;

  DailyQuiz(this.quizTraits, this.correctCharacters);
}

List<DailyQuiz> dailyQuizzes = [
  DailyQuiz([
    QuizTrait(Trait('Arsenal',[1]), 1),
    QuizTrait(Trait('Sureshot',[2,4]), 4),
    
    QuizTrait(Trait('Aegis',[2,3,4,5]), 3),
    QuizTrait(Trait('Brawler',[2,4,6,8]), 2),
    QuizTrait(Trait('Ox Force',[2,4,6,8]), 2),
    QuizTrait(Trait('Ace',[1,4]),1),
    QuizTrait(Trait('Civilian',[1,2,3]),1),
    QuizTrait(Trait('LaserCorps',[3,5,7,9]),2),
    QuizTrait(Trait('Underground',[3,4,5,6]),2),
    QuizTrait(Trait('Star Guardian',[3,5,7,9]),1),
    QuizTrait(Trait('Prankster',[2,3]),1),
    QuizTrait(Trait('Mascot',[2,4,6,8]),1),
    
    
  ], [
    [
    "Sivir",
    "Vi",
    "Alistar",
    "Senna",
    "Ekko",
    "Samira",
    "Sejuani",
    "Aphelios",
    ],[
    "Sivir",
    "Vi",
    "Alistar",
    "Senna",
    "Ekko",
    "Samira",
    "Renekton",
    "Aphelios",
    ]
  ]),
  DailyQuiz([
    QuizTrait(Trait('Gadgeteen',[3,5]), 3),
    QuizTrait(Trait('Admin',[2,4,6]), 2),
    QuizTrait(Trait('Aegis',[2,3,4,5]), 2),
    QuizTrait(Trait('Hacker',[2,3,4]), 2),
    QuizTrait(Trait('Prankster',[2,3]), 2),
    QuizTrait(Trait('Spellslinger',[2,4,6,8]),2),
    QuizTrait(Trait('Mascot',[2,4,6,8]),2),
    QuizTrait(Trait('Heart',[2,4,6]),2),
    QuizTrait(Trait('Ox Force',[2,4,6,8]),2),
    QuizTrait(Trait('Star Guardian',[3,5,7,9]),2),
  ], [
    ["Annie",
    "Alistar",
    "Leblanc",
    "Zoe",
    "Ekko",
    "Soraka",
    "Nunu",
    "Syndra",
    ]
  ]),
  DailyQuiz([
    QuizTrait(Trait('Corrupted',[1]), 1),
    QuizTrait(Trait('Forecaster',[1]), 1),
    QuizTrait(Trait('Arsenal',[1]), 1),
    QuizTrait(Trait('Aegis',[2,3,4,5]), 3),
    QuizTrait(Trait('Sureshot',[2,4]), 2),
    QuizTrait(Trait('Ox Force',[2,4,6,8]),2),
    QuizTrait(Trait('Mascot',[2,4,6,8]),2),
    QuizTrait(Trait('Civilian',[1,2,3]),1),
    QuizTrait(Trait('Ace',[1,4]),1),
    QuizTrait(Trait('Threat',[1]),1),
    QuizTrait(Trait('Gadgeteen',[3,5]), 1),
    QuizTrait(Trait('Mecha PRIME',[3,5]), 1),
    QuizTrait(Trait('Star Guardian',[3,5,7,9]),1),
    QuizTrait(Trait('Underground',[3,4,5,6]),1),
    QuizTrait(Trait('Prankster',[2,3]), 1),
    QuizTrait(Trait('Renegade',[3,6]), 1),
    QuizTrait(Trait('Spellslinger',[2,4,6,8]),1),
  ], [[
    "Alistar",
    "Ekko",
    "Samira",
    "Aphelios",
    "Fiddlesticks",
    "Janna",
    "Leona",
    "Nunu",
  ]
]),
  DailyQuiz([
    QuizTrait(Trait('Anima Squad',[3,5,7]), 5),
    QuizTrait(Trait('Aegis',[2,3,4,5]), 2),
    QuizTrait(Trait('Prankster',[2,3]), 2),
    QuizTrait(Trait('Mascot',[2,4,6,8]), 2),
    QuizTrait(Trait('Brawler',[2,4,6,8]), 2),
    QuizTrait(Trait('Ace',[1,4]), 1),
    QuizTrait(Trait('LaserCorps',[3,5,7,9]),1),
    QuizTrait(Trait('Ox Force',[2,4,6,8]),1),
    QuizTrait(Trait('Star Guardian',[3,5,7,9]),1),
    QuizTrait(Trait('Defender',[2,4,6]), 1),
    QuizTrait(Trait('Duelist',[2,4,6,8]), 1),
    QuizTrait(Trait('Recon',[2,3,4]), 1),

  ], [[
    "Nasus",
    "Jinx",
    "Alistar",
    "Riven",
    "Vayne",
    "Miss Fortune",
    "Ekko",
    "Sejuani",
 ] ,[
    "Nasus",
    "Jinx",
    "Alistar",
    "Riven",
    "Vayne",
    "Miss Fortune",
    "Ekko",
    "Renekton",
 ]]),
  DailyQuiz([
    QuizTrait(Trait('Recon',[2,3,4]), 4),
    QuizTrait(Trait('Anima Squad',[3,5,7]), 3),
    QuizTrait(Trait('Star Guardian',[3,5,7,9]), 3),
    QuizTrait(Trait('Duelist',[2,4,6,8]), 2),
    QuizTrait(Trait('Prankster',[2,3]), 2),
    QuizTrait(Trait('LaserCorps',[3,5,7,9]),1),
    QuizTrait(Trait('Underground',[3,4,5,6]),1),
    QuizTrait(Trait('Aegis',[2,3,4,5]), 1),
    QuizTrait(Trait('Brawler',[2,4,6,8]), 1),
    QuizTrait(Trait('Defender',[2,4,6]), 1),
  ], [[
    "Jinx",
    "Ashe",
    "Ezreal",
    "Kaisa",
    "Nilah",
    "Vayne",
    "Ekko",
    "Riven",
  ]  ]),
  DailyQuiz([
    QuizTrait(Trait('Forecaster',[1]), 1),
    QuizTrait(Trait('Star Guardian',[3,5,7,9]), 5),
    QuizTrait(Trait('Spellslinger',[2,4,6,8]), 4),
    QuizTrait(Trait('Aegis',[2,3,4,5]), 2),
    QuizTrait(Trait('Heart',[2,4,6]), 2),
    QuizTrait(Trait('Ox Force',[2,4,6,8]), 2),
    QuizTrait(Trait('Mascot',[2,4,6,8]), 2),
    QuizTrait(Trait('Civilian',[1,2,3]), 1),
    QuizTrait(Trait('Gadgeteen',[3,5]), 1),
    QuizTrait(Trait('Prankster',[2,3]), 1),

  ], [[
    "Alistar",
    "Ekko",
    "Annie",
    "Yuumi",
    "Syndra",
    "Janna",
    "Taliyah",
    "Lux",
  ]  ]),
  DailyQuiz([
    QuizTrait(Trait('Brawler',[2,4,6,8]), 6),
    QuizTrait(Trait('Heart',[2,4,6]), 5),
    QuizTrait(Trait('Admin',[2,4,6]), 4),
    QuizTrait(Trait('Anima Squad',[3,5,7]), 1),
    QuizTrait(Trait('LaserCorps',[3,5,7,9]),1), 
    QuizTrait(Trait('Mecha PRIME',[3,5]), 1),
    QuizTrait(Trait('Supers',[3]), 1),
    QuizTrait(Trait('Underground',[3,4,5,6]),1),
    QuizTrait(Trait('Aegis',[2,3,4,5]), 1),
    QuizTrait(Trait('Defender',[2,4,6]), 1),
  ], [[
    "Blitzcrank",
    "Sejuani",
    "Lee Sin",
    "Vi",
    "Riven",
    "Jax",
    "Soraka",
  ],[
    "Blitzcrank",
    "Renekton",
    "Lee Sin",
    "Vi",
    "Riven",
    "Jax",
    "Soraka",
  ]   ]),
  DailyQuiz([
    QuizTrait(Trait('Duelist',[2,4,6,8]), 6),
    QuizTrait(Trait('LaserCorps',[3,5,7,9]), 3),
    QuizTrait(Trait('Hacker',[2,3,4]), 2),
    QuizTrait(Trait('Anima Squad',[3,5,7]), 1),
    QuizTrait(Trait('Gadgeteen',[3,5]), 1),
    QuizTrait(Trait('Ox Force',[2,4,6,8]),1),
    QuizTrait(Trait('Star Guardian',[3,5,7,9]), 1),
    QuizTrait(Trait('Supers',[3]), 1),
    QuizTrait(Trait('Brawler',[2,4,6,8]), 1),
    QuizTrait(Trait('Prankster',[2,3]), 1),
    QuizTrait(Trait('Recon',[2,3,4]), 1),
  ], [[
    "Gangplank",
    "Fiora",
    "Nilah",
    "Yasuo",
    "Sejuani",
    "Zed",
    "Zoe",
    "Vayne",
  ] ,[
    "Gangplank",
    "Fiora",
    "Nilah",
    "Yasuo",
    "Renekton",
    "Zed",
    "Zoe",
    "Vayne",
  ]  ]),
  DailyQuiz([
    QuizTrait(Trait('Mecha PRIME',[3,5]), 5),
    QuizTrait(Trait('Ace',[1,4]), 4),
    QuizTrait(Trait('Defender',[2,4,6]), 2),
    QuizTrait(Trait('Anima Squad',[3,5,7]), 1), 
    QuizTrait(Trait('LaserCorps',[3,5,7,9]), 1),  
    QuizTrait(Trait('Underground',[3,4,5,6]),1),
    QuizTrait(Trait('Aegis',[2,3,4,5]), 1),
    QuizTrait(Trait('Brawler',[2,4,6,8]), 1),
    QuizTrait(Trait('Renegade',[3,6]), 1),
    QuizTrait(Trait('Sureshot',[2,4]), 1),
  ], [[
    "Sett",
    "Leona",
    "Wukong",
    "Draven",
    "Jax",
    "Samira",
    "Miss Fortune",
    "Mordekaiser",
  ]  ]),
  DailyQuiz([
    QuizTrait(Trait('Corrupted',[1]), 1),
    QuizTrait(Trait('Arsenal',[1]), 1),
    QuizTrait(Trait('Threat',[1]), 1),
    QuizTrait(Trait('Mecha PRIME',[3,5]), 3),
    QuizTrait(Trait('Ace',[1,4]), 1),
    QuizTrait(Trait('Defender',[2,4,6]), 2),
    QuizTrait(Trait('Aegis',[2,3,4,5]), 2),
    QuizTrait(Trait('Sureshot',[2,4]), 2),
    QuizTrait(Trait('Ox Force',[2,4,6,8]), 2),
    QuizTrait(Trait('Mascot',[2,4,6,8]),1),
    QuizTrait(Trait('Underground',[3,4,5,6]),1),
    QuizTrait(Trait('Renegade',[3,6]), 1),

  ], [[
    "Fiddlesticks",
    "Sett",
    "Alistar",
    "Leona",
    "Wukong",
    "Aphelios",
    "Samira",
  ]  ]),
   DailyQuiz([
    QuizTrait(Trait('Ox Force',[2,4,6,8]), 6),
    QuizTrait(Trait('Arsenal',[1]), 1),
    QuizTrait(Trait('Aegis',[2,3,4,5]), 3),
    QuizTrait(Trait('Renegade',[3,6]), 3),
    QuizTrait(Trait('Gadgeteen',[3,5]), 1),
    QuizTrait(Trait('Mecha PRIME',[3,5]), 1),
    QuizTrait(Trait('Star Guardian',[3,5,7,9]), 1),
    QuizTrait(Trait('Duelist',[2,4,6,8]), 1),
    QuizTrait(Trait('Mascot',[2,4,6,8]),1),
    QuizTrait(Trait('Prankster',[2,3]), 1),
    QuizTrait(Trait('Spellslinger',[2,4,6,8]), 1),
    QuizTrait(Trait('Sureshot',[2,4]), 1),
  ], [[
    "Alistar",
    "Ekko",
    "Annie",
    "Fiora",
    "Talon",
    "Viego",
    "Aphelios",
    "Leona",
  ]  ]),
  DailyQuiz([
    QuizTrait(Trait('Mascot',[2,4,6,8]), 6),
    QuizTrait(Trait('Supers',[3]), 1),
    QuizTrait(Trait('Aegis',[2,3,4,5]), 2),
    QuizTrait(Trait('Brawler',[2,4,6,8]), 2),
    QuizTrait(Trait('Heart',[2,4,6]), 2),
    QuizTrait(Trait('Civilian',[1,2,3]), 1),
    QuizTrait(Trait('Anima Squad',[3,5,7]), 1), 
    QuizTrait(Trait('Gadgeteen',[3,5]), 1),
    QuizTrait(Trait('Ox Force',[2,4,6,8]), 1),
    QuizTrait(Trait('Star Guardian',[3,5,7,9]), 1),
    QuizTrait(Trait('Underground',[3,4,5,6]),1),
    QuizTrait(Trait('Duelist',[2,4,6,8]), 1),
  ], [[
    "Galio",
    "Vi",
    "Nasus",
    "Lee Sin",
    "Alistar",
    "Malphite",
    "Gangplank",
    "Yuumi",
    "Nunu",
  ]  ]),
 DailyQuiz([
    QuizTrait(Trait('Heart',[2,4,6]), 4),
    QuizTrait(Trait('Gadgeteen',[3,5]), 3),
    QuizTrait(Trait('Aegis',[2,3,4,5]), 2),
    QuizTrait(Trait('Spellslinger',[2,4,6,8]), 2),
    QuizTrait(Trait('Prankster',[2,3]), 2),
    QuizTrait(Trait('Ox Force',[2,4,6,8]), 2),
    QuizTrait(Trait('Mascot',[2,4,6,8]), 2),
    QuizTrait(Trait('Star Guardian',[3,5,7,9]), 2),
    QuizTrait(Trait('Admin',[2,4,6]), 1),
    QuizTrait(Trait('Underground',[3,4,5,6]),1),
    QuizTrait(Trait('Hacker',[2,3,4]), 1),

  ], [[
    "Yuumi",
    "Lulu",
    "Ekko",
    "Alistar",
    "Annie",
    "Sona",
    "Soraka",
    "Zoe",
  ]  ]),
  DailyQuiz([
    QuizTrait(Trait('LaserCorps',[3,5,7,9]), 7),
    QuizTrait(Trait('Brawler',[2,4,6,8]), 2),
    QuizTrait(Trait('Duelist',[2,4,6,8]), 2),
    QuizTrait(Trait('Hacker',[2,3,4]), 2),
    QuizTrait(Trait('Prankster',[2,3]), 2),
    QuizTrait(Trait('Ace',[1,4]), 1),
    QuizTrait(Trait('Gadgeteen',[3,5]), 1),
    QuizTrait(Trait('Star Guardian',[3,5,7,9]), 1),
    QuizTrait(Trait('Aegis',[2,3,4,5]), 1),
    QuizTrait(Trait('Recon',[2,3,4]), 1),
    QuizTrait(Trait('Sureshot',[2,4]), 1),

  ], [[
    "Ashe",
    "Yasuo",
    "Senna",
    "Zed",
    "Sejuani",
    "Renekton",
    "Mordekaiser",
    "Zoe",
    "Ekko",
  ] ,[
    "Ashe",
    "Yasuo",
    "Senna",
    "Zed",
    "Renekton",
    "Renekton",
    "Mordekaiser",
    "Zoe",
    "Ekko",
  ]  ]),
    DailyQuiz([
    QuizTrait(Trait('Supers',[3]), 3),
    QuizTrait(Trait('Underground',[3,4,5,6]), 3),
    QuizTrait(Trait('Aegis',[2,3,4,5]), 2),
    QuizTrait(Trait('Brawler',[2,4,6,8]), 2),
    QuizTrait(Trait('Heart',[2,4,6]), 2),
    QuizTrait(Trait('Mascot',[2,4,6,8]), 2),
    QuizTrait(Trait('Ox Force',[2,4,6,8]), 1),
    QuizTrait(Trait('Duelist',[2,4,6,8]), 1),
    QuizTrait(Trait('Recon',[2,3,4]), 1),
    QuizTrait(Trait('Spellslinger',[2,4,6,8]), 1),
  ], [[
    "Ezreal",
    "Sona",
    "Vi",
    "Malphite",
    "Gangplank",
    "Lee Sin",
    "Alistar",
  ]  ]),
   DailyQuiz([
    QuizTrait(Trait('Forecaster',[1]), 1),
    QuizTrait(Trait('Spellslinger',[2,4,6,8]), 4),
    QuizTrait(Trait('Gadgeteen',[3,5]), 3),
    QuizTrait(Trait('Aegis',[2,3,4,5]), 2),
    QuizTrait(Trait('Hacker',[2,3,4]), 2),
    QuizTrait(Trait('Mascot',[2,4,6,8]), 2),
    QuizTrait(Trait('Ox Force',[2,4,6,8]), 2),
    QuizTrait(Trait('Prankster',[2,3]), 2),
    QuizTrait(Trait('Civilian',[1,2,3]), 1),
    QuizTrait(Trait('Star Guardian',[3,5,7,9]), 2),
    QuizTrait(Trait('Admin',[2,4,6]), 1),  
    


  ], [[
    "Annie",
    "Alistar",
    "Ekko",
    "Janna",
    "Nunu",
    "Leblanc",
    "Taliyah",
    "Zoe",
  ] ,[
    "Annie",
    "Alistar",
    "Ekko",
    "Janna",
    "Nunu",
    "Leblanc",
    "Lux",
    "Zoe",
  ] ]),
   DailyQuiz([
    QuizTrait(Trait('Arsenal',[1]), 1),
    QuizTrait(Trait('Underground',[3,4,5,6]), 5),
    QuizTrait(Trait('Brawler',[2,4,6,8]), 2),
    QuizTrait(Trait('Aegis',[2,3,4,5]), 3),
    QuizTrait(Trait('Ox Force',[2,4,6,8]), 2),
    QuizTrait(Trait('Sureshot',[2,4]), 2),
    QuizTrait(Trait('Ace',[1,4]), 1),
    QuizTrait(Trait('LaserCorps',[3,5,7,9]), 1),
    QuizTrait(Trait('Star Guardian',[3,5,7,9]), 1),
    QuizTrait(Trait('Duelist',[2,4,6,8]), 1),
    QuizTrait(Trait('Heart',[2,4,6]), 1),
    QuizTrait(Trait('Mascot',[2,4,6,8]), 1),
    QuizTrait(Trait('Prankster',[2,3]), 1),
    QuizTrait(Trait('Recon',[2,3,4]), 1),
    QuizTrait(Trait('Spellslinger',[2,4,6,8]), 1),
  ], [[
    "Ezreal",
    "Samira",
    "Sona",
    "Kayle",
    "Vi",
    "Sejuani",
    "Ekko",
    "Alistar",
    "Aphelios"
  ] ,[
    "Ezreal",
    "Samira",
    "Sona",
    "Kayle",
    "Vi",
    "Renekton",
    "Ekko",
    "Alistar",
    "Aphelios"
  ] ]),
];
